name: Deployment Exercise 2
on: [push, workflow_dispatch]
jobs:
  lint:
    runs-on: ubuntu-latest
    steps: 
      - name: Get code
        uses: actions/checkout@v3
      - name: print files in lint
        run: ls -l
  test:
    needs: lint
    runs-on: ubuntu-latest
    steps: 
      - name: print files in test
        run: ls -l
